--try/catch
BEGIN TRY
DECLARE @N1 INT, @N2 INT, @N3 INT;
DECLARE @MAI_MARE INT;
SET @N1 = 100/0*RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();
IF @N1>@N2 SET @MAI_MARE=@N1
ELSE SET @MAI_MARE=@N2
IF @N2>@N3 SET @MAI_MARE=@N2
ELSE SET @MAI_MARE=@N3
IF @N3>@N1 SET @MAI_MARE=@N3
ELSE SET @MAI_MARE=@N1
PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'Mai mare = ' + CAST(@MAI_MARE AS VARCHAR(2)); 
PRINT 'Nu exista nici o eroare'
END TRY
BEGIN CATCH 
PRINT ERROR_NUMBER()
PRINT ERROR_SEVERITY()
PRINT ERROR_STATE()
PRINT ERROR_LINE() 
PRINT ERROR_MESSAGE() 
END CATCH

--raiserror
DECLARE @N1 INT, @N2 INT, @N3 INT;
DECLARE @MAI_MARE INT;
SET @N1 = 60 * RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();

IF @N1>@N2 SET @MAI_MARE=@N1
ELSE SET @MAI_MARE=@N2
IF @N2>@N3 SET @MAI_MARE=@N2
ELSE SET @MAI_MARE=@N3
IF @N3>@N1 SET @MAI_MARE=@N3
ELSE SET @MAI_MARE=@N1
PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'Mai mare = ' + CAST(@MAI_MARE AS VARCHAR(2)); 
BEGIN
 RAISERROR ('Numarul 1 nu poate fi egal cu numarul 2',16, 1)
END